apiVersion: v1
kind: Service
metadata:
  labels:
    run: totem-api
  name: totem-api
  namespace: totem
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32222
  selector:
    app: totem-api