apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: rms
spec:
  provider: aws
  secretObjects:
    - secretName: ecr-secret
      type: Opaque
      data:
        - objectName: host
          key: host
        - objectName: port
          key: port
        - objectName: username
          key: username
        - objectName: password
          key: password
  parameters:
    objects: |
      - objectName: "prod/totem/Postgresql"
        objectType: "secretsmanager"
        jmesPath:
          - path: "host"
            objectAlias: "host"
          - path: "port"
            objectAlias: "port"
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"