# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

#  sed s/**REGISTRY/$REGISTRY_URL/ deployment.yaml.templ > deployment.yaml

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MINHA_VAR: TESTE CONTENT

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Get Secrets
      id: get-secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          prod/totem/ECR
          ECR_URL, prod/totem/ECR

    - name: echo
      run: echo "Valor de ecr $MINHA_VAR"
    
    - uses: actions/checkout@v3

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_URL/go-app:latest .
        docker push $ECR_URL/go-app:latest
        echo "image=$ECR_URL/go-app:latest" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
      
    - name: test
      run: sed s/**REGISTRY_URL/$ECR_URL/ deployment.yaml.tmpl > teste_gh.yaml

    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test
      run: go test -v ./...
